// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  // Add your Cloudflare environment variables here
  // Example: API_KEY?: string;
  [key: string]: unknown;
}
